language: c

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1 # FA uses a modded 5.0, but Busted requires 5.1+

install:
  - sudo apt-get install luarocks
  - sudo luarocks install busted

script: busted
